name: 15-minute-cron

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/15 * * * *"
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Call cron endpoint
        run: |
          curl --request POST \
          --url 'https://akademi.3hhareketi.org/api/cron' \
          --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'
